### ISSUE TITLE
Unemploymentrate_jobagency_comparison - comments

### ISSUE THREAD

**Issue by polarstern** [QuantLet/big_data_analysis#10]
There are only 5 plots at the code and 7 png pictures...

**Comment by DanielAubin** [comment]
When i run the Code i get all the plots. Note that the last png picture is the summary Output for the linear regression (this is no plot in the code). If you run "plot(lm_unemp_arbeitsamt)" you actually get 4 more plots. All together the code produces 8 plots. 

Please let me know if anything is unclear.

**Comment by polarstern** [comment]
Then please correct meta-info about plots. Every example corresponds to one png picture, the order is important. Now it is
 Example 1: Plot of the German unemployment rate.
 −−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−
 Example 2: Boxplot of the German unemployment rate.
 −−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−
 Example 3: Scatterplot of the official German unemployment rate. 
 −−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−
 Example 4: More graphical representations of the Linear Regression.
 −−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−
 Example 5: 'Job centre' (Arbeitsamt) vs Unemployment rate.
 −−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−−

**Comment by DanielAubin** [comment]
Done. Examples should, as the name says, just give examples of what the code produces. Not every single Output. I think, seven examples are enough.

**Comment by polarstern** [comment]
In our case, every example is a description for some picture, generated by code. 
I don't have Google Trend data, that's why I can't run the code and check every example and plot.
Please change comments for generating plots at the code (Plot 1, Plot 2, ... Plot 7). Now I simply can't understand, where exactly more pictures are generated. E.g. now the last picture is described as  Plot 5: 'job centre' (Arbeitsamt) vs. Unemployment rate, which contradicts your meta-info about last picture - Example 7.

**Comment by lborke** [comment]
@polarstern: Everything is fine!
this Q is now accepted

**Comment by lborke** [comment]
@I don't have Google Trend data
If you completely run the code with
install_github("googletrend", "okugami79")
library(googletrend)
...
arbeitsamt = gettrend(keyword = "Arbeitsamt", geo = "DE", use.monthly = TRUE)
 and do some google registration
you will get the data live from Google ;-)

But it runs well, Has been checked by me

@Pictures
Also, everything fine!
plot(lm_unemp_arbeitsamt)
produces several pictures. Only a few reasonable have been selected.

**Comment by lborke** [comment]
@DanielAubin 
@polarstern 
Please don't touch anything more in this Q.

I will transform now the format of the Metainfo to YAML. And then this Q is perfect!

**Comment by DanielAubin** [comment]
Perfect. Thank you both, Lukas and Svetlana.
