### ISSUE TITLE
bestglm_lambda_down.R - A lot of warnings

### ISSUE THREAD

**Issue by polarstern** [QuantLet/big_data_analysis#2]
# load data
 Lambda_mean = read.csv("Lambda_Zeitreihe_Mai15_weekly.csv", header = TRUE, sep = ";", 
     dec = ",")
Warning message:
In scan(file, what, nmax, sep, dec, quote, skip, nlines, na.strings,  :
  EOF within quoted string
 ctest = read.csv("Google_Correlate_with_downturn.csv", header = TRUE, sep = ";", 
     dec = ",")
Warning message:
In scan(file, what, nmax, sep, dec, quote, skip, nlines, na.strings,  :
  EOF within quoted string
 plot(Lambda_mean[, 2], type = "l", pch = 1, col = "red", xaxt = "n", xlab = "Date", 
     ylab = "Lambda", main = "Financial Risk Meter", ylim = c(0, 0.15), lwd = 2)
Error in `[.data.frame`(Lambda_mean, , 2) : undefined columns selected
 axis(1, at = c(1:nrow(Lambda_mean)), labels = Lambda_mean[, 1])
Error in axis(1, at = c(1:nrow(Lambda_mean)), labels = Lambda_mean[, 1]) : 
  plot.new has not been called yet
 ctest_clean = subset(ctest, select = -c(acai, acai.berry, banorte.mexico, blow.ya.back.out, 
     X18.days.lyrics, motor.arcade, unknown, motorbike.games, te.regalo.amores.lyrics, 
     break.me.down.if.it.makes.you.feel.right, matlab.2008b, notepad.2008, lions.tigers.and.bears.lyrics, 
     unknown.1, vmware.server.2, saving.abel.18.days.lyrics, seether.breakdown.lyrics, 
     el.angel, rolling.turtle, killers.spaceman, eclipse.3.4.1, she.got.her.own, song.love.story, 
     hottest.only, got.her.own, filezilla.free, the.killers.spaceman, que.quede.claro, 
     netbeans.6.5, smallville.season.8.episode.guide, samsung.sway, acai.berry.reviews, 
     luna.eddy.lover, y.que.quede.claro, uphill.rush.game, founding.farmers.restaurant, 
     gorilla.zoe.lost, jeremy.camp.there.will.be.a.day, filezilla.free.download, casting.crowns.slow.fade, 
     thesaurus.free, my.story.by.sean.mcgee, cuidado.con.el.angel, ron.browz, uyg, 
     seether.breakdown, slow.fade, slow.fade.lyrics, smoking.my.cancer, economy.jokes, 
     lost.gorilla.zoe, framing.hanley.lollipop, pbwiki.login, tan.her.hide, slam.crunk, 
     socialvibe, alternext, gdp.2008, us.gdp.2008, mil.demonios, lost.by.gorilla.zoe, 
     synthasite.com, saving.abel.18.days), drop = TRUE)
Error in eval(expr, envir, enclos) : object 'acai' not found

 # bestGLM Regression
 regsub = regsubsets(x = ctest_clean[184:584, c(2:10)], y = Lambda_mean[1:401, 2], 
     nvmax = 4)
Error in `[.data.frame`(ctest_clean, 184:584, c(2:10)) : 
  undefined columns selected
 summary(regsub)
Error in summary(regsub) : object 'regsub' not found
 summary(regsub)$adjr2
Error in summary(regsub) : object 'regsub' not found
 
 dev.new()
 # Alternative quality criteria: BIC criteria. The smaller the value the better is the variable/model.
 plot(regsub)  
Error in plot(regsub) : object 'regsub' not found
 summary(regsub)$bic
Error in summary(regsub) : object 'regsub' not found
 summary(regsub, all.best = TRUE, matrix = TRUE, matrix.logical = FALSE, df = NULL)
Error in summary(regsub, all.best = TRUE, matrix = TRUE, matrix.logical = FALSE,  : 
  object 'regsub' not found
 
 # Compare with Linear Regression Model down.economy -- FRM shifted 5 weeks
 # backwards = down.economy shifted 5 weeks forwards (-5)
 lm_down_eco = lm(Lambda_mean[1:401, 2] ~ ctest_clean[179:579, "down.economy"])
Error in model.frame.default(formula = Lambda_mean[1:401, 2] ~ ctest_clean[179:579,  : 
  invalid type (NULL) for variable 'Lambda_mean[1:401, 2]'
 summary(lm_down_eco)
Error in summary(lm_down_eco) : object 'lm_down_eco' not found
 
 # plot
 dev.new()
 plot(Lambda_mean[1:401, 2] ~ ctest_clean[181:581, "down.economy"], main = "Regression", 
     ylab = "Lambda Zeitreihe (FRM)", xlab = "Suchbegriff down economy")
Error in (function (formula, data = NULL, subset = NULL, na.action = na.fail,  : 
  invalid type (NULL) for variable 'Lambda_mean[1:401, 2]'
 abline(lm_down_eco, col = "red") 
Error in abline(lm_down_eco, col = "red") : 
  object 'lm_down_eco' not found

**Comment by lborke** [comment]
Solved. Was not the fault of the code ;-)
