### ISSUE TITLE
bestglm_lambda_down.R - plot 2 should have proper title

### ISSUE THREAD

**Issue by polarstern** [QuantLet/big_data_analysis#3]

**Comment by DanielAubin** [comment]
"Summary-plot for choosing a Model"
The darker a rectangle, the higher is the probability, that the variable is included in the model (ordered by the BIC criterion).
The rows show the variables included in the model with respect of the BIP criterion. 
For example: The best model would include "bad economy", "down economy" "tough economic times" and "recession proof". 

The plot-function for interpretation makes sense if the summary(.) output is too large. This may be the case, if more than 15 predictors can be in the model.

**Comment by lborke** [comment]
adapted!
