### ISSUE TITLE
Tree_OJ.R - MetaInfo needed plus title for the first plot

### ISSUE THREAD

**Issue by lborke** [QuantLet/big_data_analysis#4]

**Comment by DanielAubin** [comment]
# ------------------------------------------------------
# Name of QuantLet: Decision Tree and Random Forest
# ------------------------------------------------------
# Published in: ISLR-Package
# ------------------------------------------------------
# Description: The data contains 1070 purchases where the customer either purchased Citrus Hill or 
                       Minute Maid Orange Juice. A number of characteristics of the customer and product   
                       are recorded
# ------------------------------------------------------
# Keywords: tree, regression, classification
# ------------------------------------------------------
# See also: https://cran.r-project.org/web/packages/ISLR/ISLR.pdf, 
                   http://statweb.stanford.edu/~lpekelis/talks/13_datafest_cart_talk.pdf
# ------------------------------------------------------
# Author: 
# ------------------------------------------------------
# Submitted:
# ------------------------------------------------------
# Datafile: Orange Juice Data
# ------------------------------------------------------
# Input: 
# ------------------------------------------------------
# Output: Summary and Plot of a classification tree and comaprison with Random Forest
# ------------------------------------------------------
# Example:
# ------------------------------------------------------

**Comment by DanielAubin** [comment]
Title for the first Plot: "Classification Tree"
