### ISSUE TITLE
bestglm_lambda_down.R - MetaInfo needed

### ISSUE THREAD

**Issue by lborke** [QuantLet/big_data_analysis#5]

**Comment by DanielAubin** [comment]
# ------------------------------------------------------
# Name of QuantLet:  Best linear Model 
# ------------------------------------------------------
# Published in: https://cran.r-project.org/web/packages/bestglm/vignettes/bestglm.pdf
# ------------------------------------------------------
# Description: Find the best linear Model by selecting predictor Variables.
# ------------------------------------------------------
# Keywords: google correlate, google trends, linear-model, risk, variable selection, scatterplot
# ------------------------------------------------------
# See also: http://quantnet.wiwi.hu-berlin.de/index.php?p=searchResults&w=keyword&id=1251
# ------------------------------------------------------
# Author: Daniel Jacob
# ------------------------------------------------------
# Submitted:
# ------------------------------------------------------
# Datafile: FinancialRiskMeter, GoogleCorrelate Dataset (search term: "donw economy")
# ------------------------------------------------------
# Input: 
# ------------------------------------------------------
# Output: Summary of the best linear model with best predictor selection. BIC plot, scatterplot
# ------------------------------------------------------
# Example:
# ------------------------------------------------------
