### ISSUE TITLE
Tree Model - comments

### ISSUE THREAD

**Issue by polarstern** [QuantLet/big_data_analysis#8]
1. Now only two plots are generated by code: 
       1) - Tree_OJ1.png
       2) - Mix of two other pics: plot from Tree_OJ2.png and legends from Tree_OJ3.png
What should we do with it?
2. I've changed some comments and deleted unnecessary info. Please have a look in order to check whether I haven't deleted something important.

**Comment by DanielAubin** [comment]
1. Done. I changed Tree_OJ3.png. to Tree_OJ2.png. 
2. Checked the code. Everything runs fine. 
Thank you.

**Comment by lborke** [comment]
this Q is also ready now :-)
