### ISSUE TITLE
Unemployment_Google_vs_Official - comments

### ISSUE THREAD

**Issue by polarstern** [QuantLet/big_data_analysis#9]
grid.arrange(arrangeGrob(Gplot_Unemp,Gplot_GoogleA_oL,leg ,ncol=3,widths=c(3/7,3/7,1/7)))
Warning message:
Stacking not well defined when ymin != 0

**Comment by DanielAubin** [comment]
Well, this is due to the stacked position and the reverse plotting in the Gplot_Unemp. I do have no negative values (i.e. the unemployment rate). Therefore i don't really see why the error message shows up. Anyway, the function plots the data just right.

**Comment by lborke** [comment]
I think, we can leave it so.
The plot function is quite complex and in the end it works. One warning is "acceptable" ;-)
